<a href="https://colab.research.google.com/github/okrafaela/Project/blob/main/Projeto1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Passo a passo para construção do código:

- Passo 1: Importar a base de dados
- Passo 2: Calcular o faturamento de cada loja
- Passo 3: Calcular a quantidade de produtos vendidos de cada loja
- Passo 4: Calcular o ticket médio dos produtos de cada loja
- Passo 5: Enviar e-mail para diretoria
- Passo 6: Enviar e-mail para cada loja

Passo 1: Importar a base de dados

In [ ]:
import pandas as pd

tabela_vendas = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Vendas.xlsx')
display(tabela_vendas)

        Código Venda       Data  ... Valor Unitário Valor Final
0                  1 2019-01-01  ...            358         358
1                  1 2019-01-01  ...            180         360
2                  1 2019-01-01  ...            368         368
3                  2 2019-01-02  ...            200         600
4                  2 2019-01-02  ...             71          71
...              ...        ...  ...            ...         ...
100994         69996 2019-12-26  ...            102         204
100995         69996 2019-12-26  ...            270        1080
100996         69996 2019-12-26  ...             87          87
100997         69997 2019-12-26  ...            108         108
100998         69997 2019-12-26  ...            133         266

[100999 rows x 7 columns]

Passo 2: Calcular o faturamento da loja

In [ ]:
tabela_faturamento = tabela_vendas[['ID Loja', 'Valor Final']].groupby('ID Loja').sum()

tabela_faturamento = tabela_faturamento.sort_values(by='Valor Final', ascending=False)

display(tabela_faturamento)

                                  Valor Final
ID Loja
Iguatemi Campinas                     1762419
Shopping Vila Velha                   1731167
Bourbon Shopping SP                   1726110
Rio Mar Recife                        1722766
Shopping SP Market                    1721763
Palladium Shopping Curitiba           1721120
Norte Shopping                        1711968
Ribeirão Shopping                     1707122
Iguatemi Esplanada                    1699681
Rio Mar Shopping Fortaleza            1698430
Shopping Center Leste Aricanduva      1682870
Novo Shopping Ribeirão Preto          1678225
Shopping Iguatemi Fortaleza           1674824
Center Shopping Uberlândia            1668921
Shopping União de Osasco              1663770
Shopping Barra                        1653103
Passei das Águas Shopping             1649014
Shopping Eldorado                     1648111
Salvador Shopping                     1646739
Shopping Center Interlagos            1640486
Shopping Ibirapuera                   1635060
Parque Dom Pedro Shopping             1631630
Shopping Recife                       1624879
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444

Passo 3: Calcular a quantidade de produtos vendidos de cada loja

In [ ]:
tabela_quantidade = tabela_vendas[['ID Loja', 'Quantidade']].groupby('ID Loja').sum()
tabela_quantidade = tabela_quantidade.sort_values(by='Quantidade',ascending=False)
display(tabela_quantidade)

                                  Quantidade
ID Loja
Shopping Vila Velha                     9224
Palladium Shopping Curitiba             9091
Norte Shopping                          9014
Shopping Center Leste Aricanduva        8938
Rio Mar Shopping Fortaleza              8937
Iguatemi Campinas                       8935
Shopping SP Market                      8927
Rio Mar Recife                          8863
Bourbon Shopping SP                     8863
Ribeirão Shopping                       8825
Novo Shopping Ribeirão Preto            8751
Shopping União de Osasco                8730
Shopping Ibirapuera                     8723
Shopping Eldorado                       8719
Salvador Shopping                       8698
Shopping Center Interlagos              8675
Shopping Barra                          8638
Shopping Iguatemi Fortaleza             8629
Center Shopping Uberlândia              8627
Passei das Águas Shopping               8618
Shopping Recife                         8581
Iguatemi Esplanada                      8580
Shopping Morumbi                        8508
Parque Dom Pedro Shopping               8388
Shopping Midway Mall                    8206

Passo 4: Calcular o ticket médio dos produtos de cada loja

In [ ]:
ticket_medio = (tabela_faturamento['Valor Final'] / tabela_quantidade ['Quantidade']).to_frame()
ticket_medio = ticket_medio.rename(columns={0:'Ticket Médio'})
display(ticket_medio)

                                  Ticket Médio
ID Loja
Bourbon Shopping SP                 194.754598
Center Shopping Uberlândia          193.453228
Iguatemi Campinas                   197.248909
Iguatemi Esplanada                  198.098019
Norte Shopping                      189.923231
Novo Shopping Ribeirão Preto        191.775226
Palladium Shopping Curitiba         189.321307
Parque Dom Pedro Shopping           194.519552
Passei das Águas Shopping           191.345324
Ribeirão Shopping                   193.441586
Rio Mar Recife                      194.377299
Rio Mar Shopping Fortaleza          190.044758
Salvador Shopping                   189.323868
Shopping Barra                      191.375666
Shopping Center Interlagos          189.105014
Shopping Center Leste Aricanduva    188.282614
Shopping Eldorado                   189.025232
Shopping Ibirapuera                 187.442394
Shopping Iguatemi Fortaleza         194.092479
Shopping Midway Mall                193.814404
Shopping Morumbi                    186.464974
Shopping Recife                     189.357767
Shopping SP Market                  192.871401
Shopping União de Osasco            190.580756
Shopping Vila Velha                 187.680724

Função enviar e-mail

In [ ]:
def enviar_email(nome_da_loja, tabela):
  import smtplib
  import email.message

  server = smtplib.SMTP('smtp.gmail.com:587')  
  corpo_email = f"""
  <p>Prezados,</p>
  <p>Segue relatório de vendas.</p>
  {tabela.to_html()}
  <p>Qualquer dúvida estou à disposição.</p>
  """
  
  msg = email.message.Message()
  msg['Subject'] = f"Relatório de Vendas - {nome_da_loja}"
  msg['From'] = 'rafaelarosenberg323@gmail.com'
  msg['To'] = 'rosenberg.rafaela@hotmail.com'
  password = "senha"
  msg.add_header('Content-Type', 'text/html')
  msg.set_payload(corpo_email )
  
  s = smtplib.SMTP('smtp.gmail.com: 587')
  s.starttls()
  # Login Credentials for sending the mail
  s.login(msg['From'], password)
  s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))
  print('Email enviado')

Passo 5: Enviar e-mail para diretoria

In [ ]:
tabela_completa = tabela_faturamento.join(tabela_quantidade).join(ticket_medio)
enviar_email('Diretoria',tabela_completa)

Email enviado

Passo 6: Enviar e-mail para cada loja

In [ ]:
loja = 'Rio Mar Recife'
tabela_loja = tabela_vendas.loc[tabela_vendas['ID Loja'] == loja, ['ID Loja', 'Quantidade', 'Valor Final']]
tabela_loja = tabela_loja.groupby('ID Loja').sum()
display(tabela_loja)

                Quantidade  Valor Final
ID Loja
Rio Mar Recife        8863      1722766